import React, { useEffect } from 'react';
import { useUIStore } from '@/stores/useUIStore';
import { useContractStore } from '@/stores/useContractStore';
import { ContractStatus } from '@/types/crm';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import {
  X,
  CheckCircle2,
  Calendar,
  DollarSign,
  Mail,
  Phone,
  Linkedin,
  FileText,
  Clock,
  Sparkles,
  Plus,
} from 'lucide-react';

export const ContractDrawer: React.FC = () => {
  const { isDrawerOpen, closeDrawer, openQuickRenewModal, openAmendmentModal } = useUIStore();
  const { selectedContract, updateContractStatus } = useContractStore();

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') closeDrawer();
    };
    if (isDrawerOpen) {
      document.body.style.overflow = 'hidden';
      window.addEventListener('keydown', handleKeyDown);
    }
    return () => {
      document.body.style.overflow = 'unset';
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [isDrawerOpen, closeDrawer]);

  if (!isDrawerOpen || !selectedContract) return null;

  const steps: { status: ContractStatus; label: string }[] = [
    { status: 'DRAFT', label: '1. Draft' },
    { status: 'IN_REVIEW', label: '2. Legal Review' },
    { status: 'ACTIVE', label: '3. Active' },
    { status: 'RENEWED', label: '4. Renewal' },
  ];

  const getStepIndex = (status: ContractStatus) => {
    switch (status) {
      case 'DRAFT':
        return 0;
      case 'IN_REVIEW':
        return 1;
      case 'ACTIVE':
      case 'EXPIRING_SOON':
        return 2;
      case 'RENEWED':
        return 3;
      default:
        return 0;
    }
  };

  const currentStepIdx = getStepIndex(selectedContract.status);

  const handleStatusChange = async (nextStatus: ContractStatus) => {
    await updateContractStatus(selectedContract.id, nextStatus);
  };

  const handleDownloadPDF = () => {
    const content = `CONTRACT DOCUMENT\n-----------------\nContract ID: ${selectedContract.contractNumber}\nClient: ${selectedContract.accountCorporateName}\nTitle: ${selectedContract.title}\nTotal ARR: $${selectedContract.totalValue.toLocaleString('en-US')}\nStatus: ${selectedContract.status}\nTerm: ${selectedContract.billingTerm}\nStart Date: ${selectedContract.startDate}\nEnd Date: ${selectedContract.endDate}\nAccount Owner: ${selectedContract.ownerName}\n\nGenerated by ContractPulse CRM Enterprise.`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${selectedContract.contractNumber}_Agreement.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-hidden">
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-slate-900/30 backdrop-blur-2xs transition-opacity animate-in fade-in"
        onClick={closeDrawer}
      />

      {/* Slide-over Drawer Panel */}
      <div className="fixed inset-y-0 right-0 max-w-full flex pl-10">
        <div className="w-screen max-w-xl bg-white border-l border-slate-200 shadow-drawer flex flex-col justify-between overflow-y-auto animate-in slide-in-from-right duration-200">
          {/* Top Header */}
          <div className="p-6 border-b border-slate-100 sticky top-0 bg-white/95 backdrop-blur-xs z-10">
            <div className="flex items-start justify-between gap-4">
              <div>
                <div className="flex items-center gap-2 mb-1.5 flex-wrap">
                  <span className="font-mono text-xs font-bold text-blue-600 bg-blue-50 px-2 py-0.5 rounded border border-blue-100">
                    {selectedContract.contractNumber}
                  </span>
                  <Badge variant="active" withDot size="sm">
                    {selectedContract.status}
                  </Badge>
                  <span className="px-2 py-0.5 text-[10px] font-bold bg-slate-100 text-slate-700 rounded">
                    {selectedContract.accountTier}
                  </span>
                </div>
                <h2 className="text-lg font-bold text-slate-900 leading-snug">
                  {selectedContract.title}
                </h2>
                <p className="text-xs text-slate-500 mt-0.5 flex items-center gap-1.5">
                  <span>{selectedContract.accountCorporateName}</span>
                  <span>•</span>
                  <span>Owner: {selectedContract.ownerName}</span>
                </p>
              </div>

              <button
                onClick={closeDrawer}
                className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors cursor-pointer"
                title="Close drawer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Stepper Visual Horizontal */}
            <div className="mt-6 pt-4 border-t border-slate-100">
              <div className="flex items-center justify-between relative">
                {/* Background Connecting Line */}
                <div className="absolute left-4 right-4 top-3.5 h-0.5 bg-slate-200 -z-0" />
                <div
                  className="absolute left-4 top-3.5 h-0.5 bg-blue-600 transition-all duration-300 -z-0"
                  style={{
                    width: `${(currentStepIdx / (steps.length - 1)) * 92}%`,
                  }}
                />

                {steps.map((step, idx) => {
                  const isCompleted = idx < currentStepIdx;
                  const isCurrent = idx === currentStepIdx;

                  return (
                    <div key={step.status} className="flex flex-col items-center z-10">
                      <button
                        onClick={() => handleStatusChange(step.status)}
                        className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold transition-all cursor-pointer ${
                          isCompleted
                            ? 'bg-emerald-600 text-white shadow-2xs'
                            : isCurrent
                              ? 'bg-blue-600 text-white ring-4 ring-blue-100 shadow-2xs'
                              : 'bg-white text-slate-400 border-2 border-slate-300 hover:border-slate-400'
                        }`}
                        title={`Click to set status to ${step.label}`}
                      >
                        {isCompleted ? <CheckCircle2 className="w-4 h-4" /> : idx + 1}
                      </button>
                      <span
                        className={`text-[10px] font-semibold mt-1.5 whitespace-nowrap ${
                          isCurrent
                            ? 'text-blue-600 font-bold'
                            : isCompleted
                              ? 'text-emerald-700'
                              : 'text-slate-400'
                        }`}
                      >
                        {step.label}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          {/* Drawer Body Content */}
          <div className="p-6 space-y-6 flex-1">
            {/* Financial Summary Cards */}
            <div>
              <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-3">
                Financial Summary
              </h3>
              <div className="grid grid-cols-2 gap-3">
                <div className="p-3.5 bg-slate-50 rounded-xl border border-slate-200/80">
                  <span className="text-[11px] text-slate-500 font-medium">Total Contract Value (ARR)</span>
                  <p className="text-lg font-extrabold text-slate-900 mt-0.5">
                    ${selectedContract.totalValue.toLocaleString('en-US')}.00
                  </p>
                </div>
                <div className="p-3.5 bg-slate-50 rounded-xl border border-slate-200/80">
                  <span className="text-[11px] text-slate-500 font-medium">Monthly Run Rate (MRR)</span>
                  <p className="text-lg font-extrabold text-slate-900 mt-0.5">
                    ${Math.round(selectedContract.monthlyValue).toLocaleString('en-US')}.00
                  </p>
                </div>
                <div className="p-3.5 bg-slate-50 rounded-xl border border-slate-200/80">
                  <span className="text-[11px] text-slate-500 font-medium">Billing Term</span>
                  <p className="text-sm font-bold text-slate-800 capitalize mt-0.5">
                    {selectedContract.billingTerm.toLowerCase()} Schedule
                  </p>
                </div>
                <div className="p-3.5 bg-slate-50 rounded-xl border border-slate-200/80 flex items-center justify-between">
                  <div>
                    <span className="text-[11px] text-slate-500 font-medium">Auto-Renewal</span>
                    <p className="text-sm font-bold text-emerald-700 mt-0.5">
                      {selectedContract.autoRenew ? 'Enabled (Active)' : 'Disabled'}
                    </p>
                  </div>
                  <span className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
                </div>
              </div>
            </div>

            {/* Contract Duration */}
            <div className="p-4 rounded-xl border border-slate-200/80 bg-blue-50/40 flex items-center justify-between text-xs">
              <div className="flex items-center gap-2.5">
                <Calendar className="w-4 h-4 text-blue-600" />
                <div>
                  <span className="font-semibold text-slate-900">Term Duration:</span>
                  <span className="text-slate-600 ml-1.5">
                    {selectedContract.startDate} → {selectedContract.endDate}
                  </span>
                </div>
              </div>
              <span className="px-2 py-0.5 font-bold bg-blue-100 text-blue-800 rounded-full text-[10px]">
                12 Months
              </span>
            </div>

            {/* Key Stakeholders */}
            <div>
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider">
                  Key Stakeholders
                </h3>
                <span className="text-xs font-semibold text-blue-600">3 Verified</span>
              </div>

              <div className="space-y-2.5">
                {selectedContract.contacts && selectedContract.contacts.length > 0 ? (
                  selectedContract.contacts.map((contact) => (
                    <div
                      key={contact.id}
                      className="p-3 bg-white rounded-xl border border-slate-200/90 shadow-2xs flex items-center justify-between gap-3 hover:border-slate-300 transition-colors"
                    >
                      <div className="flex items-center gap-3">
                        <img
                          src={
                            contact.avatarUrl ||
                            'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80'
                          }
                          alt={contact.fullName}
                          className="w-9 h-9 rounded-full object-cover ring-1 ring-slate-200"
                        />
                        <div>
                          <div className="flex items-center gap-1.5">
                            <span className="text-xs font-bold text-slate-900">
                              {contact.fullName}
                            </span>
                            <span className="px-1.5 py-0.2 text-[9px] font-bold rounded bg-slate-100 text-slate-700">
                              {contact.roleType.replace('_', ' ')}
                            </span>
                          </div>
                          <p className="text-[11px] text-slate-500">{contact.jobTitle}</p>
                        </div>
                      </div>

                      <div className="flex items-center gap-1">
                        <a
                          href={`mailto:${contact.email}`}
                          className="p-1.5 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors"
                          title={contact.email}
                        >
                          <Mail className="w-3.5 h-3.5" />
                        </a>
                        {contact.phone && (
                          <a
                            href={`tel:${contact.phone}`}
                            className="p-1.5 text-slate-400 hover:text-emerald-600 hover:bg-emerald-50 rounded transition-colors"
                            title={contact.phone}
                          >
                            <Phone className="w-3.5 h-3.5" />
                          </a>
                        )}
                        {contact.linkedinUrl && (
                          <a
                            href={contact.linkedinUrl}
                            target="_blank"
                            rel="noreferrer"
                            className="p-1.5 text-slate-400 hover:text-blue-700 hover:bg-blue-50 rounded transition-colors"
                            title="LinkedIn"
                          >
                            <Linkedin className="w-3.5 h-3.5" />
                          </a>
                        )}
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="p-4 bg-slate-50 rounded-xl text-center text-xs text-slate-500">
                    No individual contacts linked.
                  </div>
                )}
              </div>
            </div>

            {/* Amendments & Audit Timeline */}
            <div>
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider">
                  Amendments & History Timeline
                </h3>
                <button
                  onClick={openAmendmentModal}
                  className="inline-flex items-center gap-1 text-xs font-bold text-blue-600 hover:text-blue-800 transition-colors cursor-pointer"
                >
                  <Plus className="w-3 h-3" />
                  <span>Add Amendment</span>
                </button>
              </div>

              <div className="relative pl-6 space-y-4 before:absolute before:left-2 before:top-2 before:bottom-2 before:w-0.5 before:bg-slate-200">
                {selectedContract.amendments && selectedContract.amendments.length > 0 ? (
                  selectedContract.amendments.map((item) => (
                    <div key={item.id} className="relative group">
                      {/* Timeline Dot */}
                      <span className="absolute -left-6 top-1.5 w-3 h-3 rounded-full bg-blue-600 border-2 border-white ring-2 ring-blue-100" />
                      <div className="p-3 bg-slate-50 rounded-xl border border-slate-200/80">
                        <div className="flex items-center justify-between gap-2">
                          <span className="text-xs font-bold text-slate-900">
                            {item.amendmentTitle}
                          </span>
                          {item.valueDelta !== 0 && (
                            <span className="text-xs font-extrabold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-full">
                              +${item.valueDelta.toLocaleString('en-US')} ARR
                            </span>
                          )}
                        </div>
                        {item.description && (
                          <p className="text-xs text-slate-600 mt-1 leading-relaxed">
                            {item.description}
                          </p>
                        )}
                        <div className="flex items-center gap-2 mt-2 pt-2 border-t border-slate-200/60 text-[10px] text-slate-400 font-medium">
                          <Clock className="w-3 h-3" />
                          <span>{item.effectiveDate}</span>
                          <span>•</span>
                          <span>By {item.authorName}</span>
                        </div>
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="text-xs text-slate-400 py-2">No amendments recorded yet.</div>
                )}
              </div>
            </div>
          </div>

          {/* Drawer Sticky Footer Action Controls */}
          <div className="p-5 border-t border-slate-100 bg-white/95 backdrop-blur-xs sticky bottom-0 z-10 flex items-center justify-between gap-3">
            <Button
              variant="outline"
              size="sm"
              leftIcon={<FileText className="w-4 h-4" />}
              onClick={handleDownloadPDF}
            >
              Export PDF
            </Button>

            <div className="flex items-center gap-2">
              <Button
                variant="secondary"
                size="sm"
                leftIcon={<DollarSign className="w-3.5 h-3.5" />}
                onClick={openAmendmentModal}
              >
                Amendment
              </Button>
              <Button
                variant="primary"
                size="sm"
                leftIcon={<Sparkles className="w-3.5 h-3.5" />}
                onClick={openQuickRenewModal}
                className="shadow-xs font-bold"
              >
                Quick Renew
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
